services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: secureloguser
      POSTGRES_PASSWORD: securelogpass
      POSTGRES_DB: securelogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secureloguser -d securelogdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: