# Fly.io configuration for SecureLog API
# Deploy with: fly deploy

app = "securelog-api"
primary_region = "iad" # Change to your preferred region (iad=Virginia, lhr=London, syd=Sydney, etc.)

[build]
  # Set the build context to the server directory
  dockerfile = "Dockerfile"
  context = "server"

[env]
  PORT = "8000"
  # DATABASE_URL will be set automatically when you attach Postgres

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
