name: Server Lint

on:
  push:
    branches: [ "**" ]
    paths:
      - 'server/**'
      - '.github/workflows/server-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: server/requirements.txt
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          pip install -r requirements.txt
      
      - name: Run flake8
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Run flake8 (full)
        run: flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Check code formatting with black
        run: black --check src
      
      - name: Check import sorting with isort
        run: isort --check-only src
